services:
  database:
    image: postgres
    container_name: database_rentalCars
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin_db
      - POSTGRES_PASSWORD=rentalcars
      - POSTGRES_DB=rentalCars_db
    volumes:
      - pgdata:/data/postgres

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rentalcars
    container_name: rentalCars
    ports:
      - 3333:3333
    depends_on:
      - database
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local